Repository mastodon/mastodon-ios, pull requests merged in 2021-08, with the labels that each got.

#252 minor grammar fix
  README.md
Labels: documentation

#257 Fix reply message scope not be respected issue
  Mastodon.xcodeproj/xcuserdata/mainasuk.xcuserdatad/xcschemes/xcschememanagement.plist
  Mastodon/Diffiable/Item/SettingsItem.swift
  Mastodon/Extension/MetaLabel.swift
  Mastodon/Scene/Compose/ComposeViewModel.swift
  Mastodon/Scene/Onboarding/Register/MastodonRegisterViewController.swift
  Mastodon/Scene/Settings/SettingsViewController.swift
  Mastodon/Scene/Settings/SettingsViewModel.swift
  Podfile.lock
Labels: bug, scene:compose, scene:onboarding

#262 Set approval required server default hidden when register and other bugfix
  Mastodon.xcodeproj/project.pbxproj
  Mastodon/Diffiable/Item/ComposeStatusPollItem.swift
  Mastodon/Diffiable/Section/Compose/AutoCompleteSection.swift
  Mastodon/Diffiable/Section/Status/NotificationSection.swift
  Mastodon/Diffiable/Section/Status/StatusSection.swift
  Mastodon/Extension/MastodonSDK/Mastodon+Entity+Account.swift
  Mastodon/Extension/MetaLabel.swift
  Mastodon/Extension/UIView.swift
  Mastodon/Scene/Compose/AutoComplete/Cell/AutoCompleteTableViewCell.swift
  Mastodon/Scene/Compose/CollectionViewCell/ComposeStatusContentTableViewCell.swift
  Mastodon/Scene/Notification/TableViewCell/NotificationStatusTableViewCell.swift
  Mastodon/Scene/Onboarding/PickServer/MastodonPickServerViewModel+LoadIndexedServerState.swift
  Mastodon/Scene/Onboarding/ServerRules/MastodonServerRulesViewController.swift
  Mastodon/Scene/Onboarding/ServerRules/MastodonServerRulesViewModel.swift
  Mastodon/Scene/Profile/Header/View/ProfileStatusDashboardMeterView.swift
  Mastodon/Scene/Profile/Header/View/ProfileStatusDashboardView.swift
  Mastodon/Scene/Search/Search/View/SearchRecommendCollectionHeader.swift
  Mastodon/Scene/Settings/View/AppearanceView.swift
  Mastodon/Scene/Settings/View/Cell/SettingsToggleTableViewCell.swift
Labels: bug, enhancement

#269 Fix issue #255
  Mastodon/Scene/Share/View/Container/MosaicImageViewContainer.swift
Labels: bug

#270 Make server list sort by language
  Mastodon.xcodeproj/project.pbxproj
  Mastodon.xcodeproj/xcuserdata/mainasuk.xcuserdatad/xcschemes/xcschememanagement.plist
  Mastodon.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Mastodon/Diffiable/Section/Search/RecommendAccountSection.swift
  Mastodon/Protocol/StatusProvider/StatusProviderFacade.swift
  Mastodon/Scene/Onboarding/PickServer/MastodonPickServerViewModel+LoadIndexedServerState.swift
  Mastodon/Scene/Onboarding/PickServer/MastodonPickServerViewModel.swift
  Mastodon/Scene/Onboarding/PickServer/TableViewCell/PickServerCell.swift
  Mastodon/Scene/Profile/Header/ProfileHeaderViewController.swift
  Mastodon/Scene/Profile/Header/ProfileHeaderViewModel.swift
  Mastodon/Scene/Search/Search/CollectionViewCell/SearchRecommendAccountsCollectionViewCell.swift
  Mastodon/Scene/Search/Search/SearchViewController+Follow.swift
  Mastodon/Scene/Search/Search/SearchViewController.swift
  Mastodon/Scene/Search/Search/SearchViewModel.swift
  Mastodon/Scene/Search/Search/View/SearchRecommendCollectionHeader.swift
  Mastodon/Scene/Share/View/ToolBar/ActionToolBarContainer.swift
  Mastodon/Scene/Share/ViewModel/VideoPlayerViewModel.swift
  Mastodon/Service/AudioPlaybackService.swift
  Mastodon/Service/VideoPlaybackService.swift
  README.md
Labels: bug, enhancement

#276 Fix issue 275
  Localization/app.json
  Mastodon.xcodeproj/xcuserdata/mainasuk.xcuserdatad/xcschemes/xcschememanagement.plist
  Mastodon/Diffiable/Item/ComposeStatusPollItem.swift
  Mastodon/Scene/Compose/ComposeViewModel+PublishState.swift
  Mastodon/Scene/Compose/ComposeViewModel.swift
  Mastodon/Service/APIService/APIService+Media.swift
  Mastodon/Service/APIService/APIService+Status+Publish.swift
  Mastodon/Service/MastodonAttachmentService/MastodonAttachmentService+UploadState.swift
  Mastodon/Service/MastodonAttachmentService/MastodonAttachmentService.swift
  MastodonIntent/SendPostIntentHandler.swift
  MastodonSDK/Sources/MastodonSDK/API/Mastodon+API+Media.swift
  MastodonSDK/Sources/MastodonSDK/API/Mastodon+API+Statuses.swift
  MastodonSDK/Sources/MastodonSDK/Response/Mastodon+Response+Content.swift
  ShareActionExtension/Scene/ShareViewModel.swift
Labels: bug, enhancement, scene:compose

#280 Fix date components issue
  Mastodon/Extension/Date.swift
Labels: bug, scene:home, Priority: High

#286 Fix GIFV may interrupt music playback issue
  Mastodon/Scene/Share/ViewModel/VideoPlayerViewModel.swift
  Mastodon/Service/AudioPlaybackService.swift
Labels: bug
