Repository mastodon/mastodon-ios, pull requests merged in 2022-11, with the labels that each got.

#496 Fix typos in Setup.md
  Documentation/Setup.md
Labels: documentation

#489 Add support for entering text to search via drag-and-drop
  Mastodon/Scene/Root/RootSplitViewController.swift
  Mastodon/Scene/Search/Search/SearchViewController.swift
  Mastodon/Scene/Search/SearchDetail/SearchDetailViewController.swift
  Mastodon/Supporting Files/SceneDelegate.swift
Labels: enhancement

#492 Use LPLinkMetadata to improve sharing behavior
  Mastodon/Protocol/Provider/DataSourceFacade+Status.swift
  MastodonSDK/Sources/MastodonUI/View/Content/NotificationView.swift
  MastodonSDK/Sources/MastodonUI/View/Content/StatusAuthorView.swift
  MastodonSDK/Sources/MastodonUI/View/Content/StatusView.swift
Labels: enhancement

#503 Add TestFlight build CI workflow
  .github/scripts/build-release.sh
  .github/scripts/setup.sh
  .github/support/ExportOptions.plist
  .github/workflows/develop-build.yml
  Mastodon.xcodeproj/project.pbxproj
  Mastodon.xcodeproj/xcuserdata/mainasuk.xcuserdatad/xcschemes/xcschememanagement.plist
  Mastodon/Info.plist
  Mastodon/Scene/Report/Report/ReportViewModel.swift
  MastodonIntent/Info.plist
  MastodonSDK/Sources/MastodonCore/Service/API/APIService+Report.swift
  MastodonTests/Info.plist
  MastodonUITests/Info.plist
  NotificationService/Info.plist
  Podfile
  Podfile.lock
  ShareActionExtension/Info.plist
Labels: enhancement

#532 Fix deploy build version cannot bump issue
  .github/scripts/build-release.sh
  .github/support/ExportOptions.plist
  .github/workflows/develop-build.yml
  Mastodon.xcodeproj/project.pbxproj
  Mastodon/Info.plist
  MastodonIntent/Info.plist
  MastodonTests/Info.plist
  MastodonUITests/Info.plist
  NotificationService/Info.plist
  ShareActionExtension/Info.plist
Labels: bug

#500 Add support for scrolling the discovery tab to the top/first tab
  Mastodon/Protocol/ScrollViewContainer.swift
  Mastodon/Scene/Discovery/DiscoveryViewController.swift
  Mastodon/Scene/Search/Search/SearchViewController.swift
Labels: enhancement

#486 feat: handle paste event and insert images on the clipboard
  Mastodon.xcodeproj/project.pbxproj
  Mastodon/Scene/Compose/ComposeViewController.swift
  Mastodon/Scene/Compose/View/MetaTextView+PasteExtensions.swift
Labels: enhancement

#585 Fix authenticated user account not reloaded
  Mastodon/Scene/Profile/ProfileViewController.swift
  Mastodon/Scene/Root/MainTab/MainTabBarController.swift
  Mastodon/Supporting Files/SceneDelegate.swift
  MastodonSDK/Sources/MastodonCore/Extension/CoreDataStack/MastodonUser+Property.swift
  MastodonSDK/Sources/MastodonCore/Service/API/APIService+Account.swift
  MastodonSDK/Sources/MastodonCore/Service/InstanceService.swift
Labels: bug

#602 Update purple logo
  Localization/StringsConvertor/input/Base.lproj/app.json
  Mastodon/Scene/Onboarding/Welcome/WelcomeViewController.swift
  MastodonSDK/Sources/MastodonAsset/Assets.xcassets/Scene/Welcome/mastodon.logo.black.imageset/Contents.json
  MastodonSDK/Sources/MastodonAsset/Assets.xcassets/Scene/Welcome/mastodon.logo.black.imageset/mastodon.logo.black.pdf
  MastodonSDK/Sources/MastodonAsset/Assets.xcassets/Scene/Welcome/mastodon.logo.black.large.imageset/Contents.json
  MastodonSDK/Sources/MastodonAsset/Assets.xcassets/Scene/Welcome/mastodon.logo.black.large.imageset/mastodon.logo.black.large.pdf
  MastodonSDK/Sources/MastodonAsset/Assets.xcassets/Scene/Welcome/mastodon.logo.imageset/Contents.json
  MastodonSDK/Sources/MastodonAsset/Assets.xcassets/Scene/Welcome/mastodon.logo.imageset/logo.small.pdf
  MastodonSDK/Sources/MastodonAsset/Assets.xcassets/Scene/Welcome/mastodon.logo.imageset/logotypeFull1.pdf
  MastodonSDK/Sources/MastodonAsset/Assets.xcassets/Scene/Welcome/mastodon.logo.large.imageset/Contents.json
  MastodonSDK/Sources/MastodonAsset/Assets.xcassets/Scene/Welcome/mastodon.logo.large.imageset/logotypeFull1.large.pdf
  MastodonSDK/Sources/MastodonAsset/Generated/Assets.swift
  MastodonSDK/Sources/MastodonLocalization/Generated/Strings.swift
  MastodonSDK/Sources/MastodonLocalization/Resources/Base.lproj/Localizable.strings
Labels: enhancement

#618 Fix compose content could not post media only issue
  MastodonSDK/Sources/MastodonUI/Scene/ComposeContent/ComposeContentViewModel.swift
Labels: bug, scene:compose

#619 fix: TabBar has noticeable delay when selecting next tab
  Mastodon/Scene/Root/MainTab/MainTabBarController.swift
Labels: bug

#621 Fix thread logic to use the original order
  Mastodon/Scene/Thread/ThreadViewModel+LoadThreadState.swift
  Mastodon/Scene/Thread/ThreadViewModel.swift
Labels: bug

#631 Tag the build number automatically
  .github/scripts/build-release.sh
  .github/workflows/develop-build.yml
Labels: enhancement

#633 Bump the timeout interval for all requests to 60s
  MastodonSDK/Sources/MastodonSDK/API/Mastodon+API.swift
Labels: enhancement

#634 Fix hashtag auto complete issue
  MastodonSDK/Sources/MastodonUI/Scene/ComposeContent/ComposeContentViewController.swift
Labels: bug

#552 Improve accessibility of the notifications tab
  Localization/StringsConvertor/input/Base.lproj/app.json
  Localization/app.json
  Mastodon/Coordinator/SceneCoordinator.swift
  Mastodon/Scene/Root/MainTab/MainTabBarController.swift
  Mastodon/Scene/Root/Sidebar/SidebarViewModel.swift
  Mastodon/Scene/Share/View/Content/NotificationView+Configuration.swift
  Mastodon/Scene/Share/View/TableviewCell/StatusThreadRootTableViewCell.swift
  Mastodon/Supporting Files/SceneDelegate.swift
  MastodonSDK/Package.resolved
  MastodonSDK/Sources/CoreDataStack/Entity/Transient/MastodonNotificationType.swift
  MastodonSDK/Sources/MastodonLocalization/Generated/Strings.swift
  MastodonSDK/Sources/MastodonLocalization/Resources/Base.lproj/Localizable.strings
  MastodonSDK/Sources/MastodonUI/View/Content/NotificationView+ViewModel.swift
  MastodonSDK/Sources/MastodonUI/View/Content/NotificationView.swift
  MastodonSDK/Sources/MastodonUI/View/Content/StatusView+ViewModel.swift
  MastodonSDK/Sources/MastodonUI/View/Content/StatusView.swift
Labels: accessibility

#620 Add doc about how-it-works
  Documentation/How-it-works.md
Labels: documentation

#674 Fix no downscaling for raw image from camera issue
  Mastodon/Scene/Compose/ComposeViewController.swift
  MastodonSDK/Sources/MastodonUI/Extension/UIImage.swift
  MastodonSDK/Sources/MastodonUI/Scene/ComposeContent/Attachment/AttachmentViewModel+Compress.swift
  MastodonSDK/Sources/MastodonUI/Scene/ComposeContent/Attachment/AttachmentViewModel+Load.swift
  MastodonSDK/Sources/MastodonUI/Scene/ComposeContent/Attachment/AttachmentViewModel.swift
  MastodonSDK/Sources/MastodonUI/Scene/ComposeContent/ComposeContentViewController.swift
  MastodonSDK/Sources/MastodonUI/Scene/ComposeContent/ComposeContentViewModel.swift
  ShareActionExtension/Scene/ShareViewController.swift
Labels: bug, scene:compose

#684 Fix share extension reentry crash issue
  MastodonSDK/Sources/MastodonCore/AppContext.swift
  ShareActionExtension/Scene/ShareViewController.swift
Labels: bug

#692 Fix profile page scroll to top cannot trigger issue
  Mastodon/Scene/Profile/ProfileViewController.swift
Labels: bug
